server:
  port: 8080
  context-path: /SpringBootTest
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 120 
  
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true     
  datasource:
    name: datasource
    url: jdbc:mysql://192.168.1.211:3309/gjx?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: aaaaaa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
  
mybatis:
  mapper-locations: classpath*:com/ycnet/mapper/*Mapper.xml
  type-aliases-package: com.ycnet.mapper